# Basic website settings
title: Mahendra Gehlot - Data Scientist
description: Portfolio website of Mahendra Gehlot, Data Scientist specialized in Machine Learning, Time Series Prediction, LLMs, and Computer Vision
author: Mahendra Gehlot

# GitHub Pages settings
url: "https://mahendra-gehlot.github.io" # GitHub Pages domain
baseurl: "" # Leave empty if your site is in the root

# Social profiles
social:
  github: mahendra-gehlot
  linkedin: mahendra-gehlot
  email: connect.mge@gmail.com
  skype: live:mahendra2baori
  phone: +917737101405

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude files from being published
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
